// Code generated by "stringer -type=Token"; DO NOT EDIT

package token

import "fmt"

const _Token_name = "ILLEGALEOLEOFCOMMENTCHARCOMMADASHEQUALSLITERALNUMBERPLUSSTRALTALT_GRALT_IS_METAASCHARSETCOMPOSECONTROLCTRLLCTRLRFORINCLUDEKEYCODEKEYMAPSPLAINSHIFTSHIFTLSHIFTRSTRINGSTRINGSTOUSUAL"

var _Token_index = [...]uint8{0, 7, 10, 13, 20, 24, 29, 33, 39, 46, 52, 56, 59, 62, 68, 79, 81, 88, 95, 102, 107, 112, 115, 122, 129, 136, 141, 146, 152, 158, 164, 171, 173, 178}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return fmt.Sprintf("Token(%d)", i)
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
